[workspace]
members = [
  "crates/zann-crypto",
  "crates/zann-core",
  "crates/zann-db",
  "crates/zann-keystore",
  "crates/zann-server",
  "crates/zann-cli",
]
exclude = [
  "apps/desktop/src-tauri",
]
resolver = "2"
