[package]
name = "zann-keystore"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
anyhow = "1"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
thiserror = "1"

[target.'cfg(target_os = "macos")'.dependencies]
keyring = "2"
